# Generated by Django 5.2 on 2025-04-07 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(related_name='stadiums', to='stadiums.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stadiums', to=settings.AUTH_USER_MODEL)),
                ('sport_types', models.ManyToManyField(related_name='stadiums', to='stadiums.sporttype')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stadium_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadiums.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_stadiums', to=settings.AUTH_USER_MODEL)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='stadiums.stadium')),
            ],
            options={
                'unique_together': {('stadium', 'manager')},
            },
        ),
    ]
